name: Build and Deploy Documentation

on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
    
    - name: Debug - Check file structure
      run: |
        echo "Current directory:"
        pwd
        echo "Files in root:"
        ls -la
        echo "Files in docs directory:"
        ls -la docs/
        echo "Checking if Doxyfile exists:"
        test -f docs/Doxyfile && echo "Doxyfile exists" || echo "Doxyfile not found"
    
    - name: Build Documentation
      run: |
        doxygen docs/Doxyfile
    
    - name: Fix Korean translations
      run: |
        cd docs/html
        # Replace "문서화" with "Documentation" in all HTML files
        find . -name "*.html" -type f -exec sed -i 's/문서화/Documentation/g' {} \;
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
